steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/majornews/majornewsdata:latest', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/majornews/majornewsdata:latest']

  # Start container on existing VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'compute', 'instances', 'add-tags', 'someinstance',
         '--tags', 'http-server,https-server',
         '--zone=us-central1-a']