steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/majornews/majornewsdata:latest', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/majornews/majornewsdata:latest']

  # Start container on existing VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'compute', 'instances', 'add-tags', '<INSTANCE_NAME>', '--tags', 'docker']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'compute', 'ssh', '--zone', 'us-central1-a', '<INSTANCE_NAME>', '--command', 'sudo docker run -d -p 80:80 gcr.io/majornews/majornewsdata']