steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/majornews/majornewsdata:latest', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/majornews/majornewsdata:latest']

  # Start container on existing VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta compute ssh someinstance --zone=us-central1-a --command='docker run -p 80:80 gcr.io/majornews/majornewsdata:latest'
    id: 'docker-run'
    waitFor:
      - '-'